2025-01-16 02:53:02,992 - __main__ - INFO - Запуск main()
2025-01-16 02:53:03,024 - __main__ - INFO - Инициализация базы данных
2025-01-16 02:53:03,082 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 02:53:03,093 - __main__ - INFO - Подключение middleware
2025-01-16 02:53:03,093 - __main__ - INFO - Регистрация хендлеров
2025-01-16 02:53:03,093 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 02:53:03,095 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 02:53:03,095 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 02:53:03,095 - aiogram.dispatcher - INFO - Start polling
2025-01-16 02:53:03,798 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 02:55:26,404 - aiogram.event - INFO - Update id=785582077 is handled. Duration 406 ms by bot id=7987337779
2025-01-16 02:55:28,431 - httpx - INFO - HTTP Request: POST https://ngw.devices.sberbank.ru:9443/api/v2/oauth "HTTP/1.1 200 OK"
2025-01-16 02:55:31,576 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 02:55:32,679 - aiogram.event - INFO - Update id=785582078 is handled. Duration 4547 ms by bot id=7987337779
2025-01-16 02:55:42,133 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 02:55:42,266 - aiogram.event - INFO - Update id=785582079 is handled. Duration 1608 ms by bot id=7987337779
2025-01-16 02:55:51,370 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 02:55:51,498 - aiogram.event - INFO - Update id=785582080 is handled. Duration 1718 ms by bot id=7987337779
2025-01-16 02:56:04,577 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 02:56:04,719 - aiogram.event - INFO - Update id=785582081 is handled. Duration 6500 ms by bot id=7987337779
2025-01-16 02:56:21,619 - httpx - INFO - HTTP Request: POST https://ngw.devices.sberbank.ru:9443/api/v2/oauth "HTTP/1.1 200 OK"
2025-01-16 02:56:23,990 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 02:56:24,232 - aiogram.event - INFO - Update id=785582082 is handled. Duration 2844 ms by bot id=7987337779
2025-01-16 02:56:51,943 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 02:56:51,943 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 02:56:52,199 - __main__ - INFO - Закрытие сессии бота
2025-01-16 02:56:52,199 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 02:56:52,199 - apscheduler.scheduler - INFO - Scheduler has been shut down
2025-01-16 03:03:43,077 - __main__ - INFO - Запуск main()
2025-01-16 03:03:43,127 - __main__ - INFO - Инициализация базы данных
2025-01-16 03:03:43,188 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 03:03:43,199 - __main__ - INFO - Подключение middleware
2025-01-16 03:03:43,200 - __main__ - INFO - Регистрация хендлеров
2025-01-16 03:03:43,200 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 03:03:43,217 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 03:03:43,218 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 03:03:43,218 - aiogram.dispatcher - INFO - Start polling
2025-01-16 03:03:43,867 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:03:47,135 - aiogram.event - INFO - Update id=785582083 is handled. Duration 358 ms by bot id=7987337779
2025-01-16 03:03:48,138 - bot.handlers.start - INFO - Пользователь 615014924 вызвал команду /start
2025-01-16 03:03:48,138 - bot.handlers.start - INFO - Пользователь 615014924 уже зарегистрирован
2025-01-16 03:03:48,262 - aiogram.event - INFO - Update id=785582084 is handled. Duration 125 ms by bot id=7987337779
2025-01-16 03:03:51,373 - aiogram.event - INFO - Update id=785582085 is handled. Duration 2140 ms by bot id=7987337779
2025-01-16 03:03:53,986 - aiogram.event - INFO - Update id=785582086 is handled. Duration 234 ms by bot id=7987337779
2025-01-16 03:03:58,914 - httpx - INFO - HTTP Request: POST https://ngw.devices.sberbank.ru:9443/api/v2/oauth "HTTP/1.1 200 OK"
2025-01-16 03:04:00,217 - httpx - INFO - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-16 03:04:00,342 - aiogram.event - INFO - Update id=785582087 is handled. Duration 1639 ms by bot id=7987337779
2025-01-16 03:04:07,206 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 03:04:07,206 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:04:07,464 - __main__ - INFO - Закрытие сессии бота
2025-01-16 03:04:07,464 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 03:04:07,464 - apscheduler.scheduler - INFO - Scheduler has been shut down
2025-01-16 03:34:35,351 - __main__ - INFO - Запуск main()
2025-01-16 03:34:35,406 - __main__ - INFO - Инициализация базы данных
2025-01-16 03:34:35,676 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 03:34:35,686 - __main__ - INFO - Подключение middleware
2025-01-16 03:34:35,687 - __main__ - INFO - Регистрация хендлеров
2025-01-16 03:34:35,687 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 03:34:35,700 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 03:34:35,700 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 03:34:35,703 - aiogram.dispatcher - INFO - Start polling
2025-01-16 03:34:37,225 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:35:44,252 - aiogram.event - INFO - Update id=785582088 is handled. Duration 968 ms by bot id=7987337779
2025-01-16 03:35:48,672 - aiogram.event - INFO - Update id=785582089 is handled. Duration 343 ms by bot id=7987337779
2025-01-16 03:35:52,152 - aiogram.event - INFO - Update id=785582090 is handled. Duration 359 ms by bot id=7987337779
2025-01-16 03:36:02,184 - aiogram.event - INFO - Update id=785582091 is not handled. Duration 547 ms by bot id=7987337779
2025-01-16 03:36:02,184 - aiogram.event - ERROR - Cause exception while process update id=785582091 by bot id=7987337779
TypeError: handle_errors() missing 1 required positional argument: 'exception'
Traceback (most recent call last):
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\bot\middlewares\registration_check.py", line 21, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "D:\Programming\Python\RunnerBot\bot\handlers\feedback.py", line 38, in process_review
    save_feedback(user_id=message.from_user.id, rating=rating, review=review)
  File "D:\Programming\Python\RunnerBot\bot\utils\db.py", line 369, in save_feedback
    cursor.execute(
sqlite3.OperationalError: no such table: feedback

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 29, in __call__
    response = await self.router.propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
TypeError: handle_errors() missing 1 required positional argument: 'exception'
2025-01-16 03:37:17,872 - aiogram.event - INFO - Update id=785582092 is not handled. Duration 0 ms by bot id=7987337779
2025-01-16 03:37:17,872 - aiogram.event - ERROR - Cause exception while process update id=785582092 by bot id=7987337779
TypeError: handle_errors() missing 1 required positional argument: 'exception'
Traceback (most recent call last):
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\bot\middlewares\registration_check.py", line 21, in __call__
    return await handler(event, data)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "D:\Programming\Python\RunnerBot\bot\handlers\feedback.py", line 38, in process_review
    save_feedback(user_id=message.from_user.id, rating=rating, review=review)
  File "D:\Programming\Python\RunnerBot\bot\utils\db.py", line 369, in save_feedback
    cursor.execute(
sqlite3.OperationalError: no such table: feedback

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 29, in __call__
    response = await self.router.propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Programming\Python\RunnerBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
TypeError: handle_errors() missing 1 required positional argument: 'exception'
2025-01-16 03:40:15,524 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:40:15,524 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 03:40:15,786 - __main__ - INFO - Закрытие сессии бота
2025-01-16 03:40:15,786 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 03:40:15,786 - apscheduler.scheduler - INFO - Scheduler has been shut down
2025-01-16 03:40:39,259 - __main__ - INFO - Запуск main()
2025-01-16 03:40:39,260 - __main__ - INFO - Инициализация базы данных
2025-01-16 03:40:39,261 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 03:40:39,271 - __main__ - INFO - Подключение middleware
2025-01-16 03:40:39,271 - __main__ - INFO - Регистрация хендлеров
2025-01-16 03:40:39,272 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 03:40:39,273 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 03:40:39,273 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 03:40:39,273 - aiogram.dispatcher - INFO - Start polling
2025-01-16 03:40:40,719 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:40:44,529 - aiogram.event - INFO - Update id=785582093 is handled. Duration 1952 ms by bot id=7987337779
2025-01-16 03:40:46,088 - aiogram.event - INFO - Update id=785582094 is handled. Duration 327 ms by bot id=7987337779
2025-01-16 03:40:47,732 - aiogram.event - INFO - Update id=785582095 is handled. Duration 327 ms by bot id=7987337779
2025-01-16 03:40:50,537 - aiogram.event - INFO - Update id=785582096 is handled. Duration 343 ms by bot id=7987337779
2025-01-16 03:41:22,970 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:41:22,970 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 03:41:23,234 - __main__ - INFO - Закрытие сессии бота
2025-01-16 03:41:23,234 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 03:41:23,234 - apscheduler.scheduler - INFO - Scheduler has been shut down
2025-01-16 03:41:45,940 - __main__ - INFO - Запуск main()
2025-01-16 03:41:45,942 - __main__ - INFO - Инициализация базы данных
2025-01-16 03:41:45,943 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 03:41:45,953 - __main__ - INFO - Подключение middleware
2025-01-16 03:41:45,954 - __main__ - INFO - Регистрация хендлеров
2025-01-16 03:41:45,954 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 03:41:45,955 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 03:41:45,955 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 03:41:45,955 - aiogram.dispatcher - INFO - Start polling
2025-01-16 03:41:47,917 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:41:52,771 - aiogram.event - INFO - Update id=785582097 is handled. Duration 969 ms by bot id=7987337779
2025-01-16 03:41:58,609 - aiogram.event - INFO - Update id=785582098 is handled. Duration 327 ms by bot id=7987337779
2025-01-16 03:42:01,616 - aiogram.event - INFO - Update id=785582099 is handled. Duration 531 ms by bot id=7987337779
2025-01-16 03:42:55,556 - aiogram.event - INFO - Update id=785582100 is handled. Duration 327 ms by bot id=7987337779
2025-01-16 03:42:58,025 - aiogram.event - INFO - Update id=785582101 is handled. Duration 344 ms by bot id=7987337779
2025-01-16 03:43:04,243 - aiogram.event - INFO - Update id=785582102 is handled. Duration 452 ms by bot id=7987337779
2025-01-16 03:44:15,467 - aiogram.event - INFO - Update id=785582103 is handled. Duration 343 ms by bot id=7987337779
2025-01-16 03:48:31,795 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:48:31,796 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 03:48:32,049 - __main__ - INFO - Закрытие сессии бота
2025-01-16 03:48:32,049 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 03:48:32,049 - apscheduler.scheduler - INFO - Scheduler has been shut down
2025-01-16 03:48:36,944 - __main__ - INFO - Запуск main()
2025-01-16 03:48:36,945 - __main__ - INFO - Инициализация базы данных
2025-01-16 03:48:36,946 - __main__ - INFO - Настройка бота и диспетчера
2025-01-16 03:48:36,957 - __main__ - INFO - Подключение middleware
2025-01-16 03:48:36,957 - __main__ - INFO - Регистрация хендлеров
2025-01-16 03:48:36,957 - bot.handlers.reminders - INFO - Запуск планировщика задач
2025-01-16 03:48:36,958 - apscheduler.scheduler - INFO - Scheduler started
2025-01-16 03:48:36,958 - __main__ - INFO - Бот запущен! Начало polling...
2025-01-16 03:48:36,958 - aiogram.dispatcher - INFO - Start polling
2025-01-16 03:48:38,480 - aiogram.dispatcher - INFO - Run polling for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:48:43,913 - aiogram.event - INFO - Update id=785582104 is handled. Duration 1312 ms by bot id=7987337779
2025-01-16 03:48:46,008 - aiogram.event - INFO - Update id=785582105 is handled. Duration 327 ms by bot id=7987337779
2025-01-16 03:48:52,313 - aiogram.event - INFO - Update id=785582106 is handled. Duration 530 ms by bot id=7987337779
2025-01-16 03:49:33,890 - aiogram.dispatcher - INFO - Polling stopped for bot @airunnerbot id=7987337779 - 'RunnerBot'
2025-01-16 03:49:33,890 - aiogram.dispatcher - INFO - Polling stopped
2025-01-16 03:49:34,153 - __main__ - INFO - Закрытие сессии бота
2025-01-16 03:49:34,153 - bot.handlers.reminders - INFO - Остановка планировщика задач
2025-01-16 03:49:34,153 - apscheduler.scheduler - INFO - Scheduler has been shut down
